config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :books do
    collection do
    end
  end

  namespace :interface do
    resources :books do
      collection do
        get :all
      end
    end
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
#  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  #layout 'two'
  def index
    @books = Book.all
    @books = Book.where("name like '%#{params[:query]}%'")
    #render layout: false//在主页中不要禁用layout
  end

  def destroy
    book = Book.find params[:id]
    book.delete
    redirect_to "/books"
  end

  def edit
    @book = Book.find params[:id]
    #render layout: "application"
  end

  def update
    @book = Book.find params[:id]
    @book.name= params[:book][:name]
    @book.author= params[:book][:author]
    @book.save
    redirect_to books_path
  end

  def new
    @book = Book.new
  end

  def create
    Book.create :name=>params[:book][:name], :author=>params[:book][:author]
    redirect_to books_path
  end

  def show
    @book = Book.find params[:id]
  end

  #form_tag时用这个
  #def create
  #  Book.create :name=>params[:name], :author=>params[:author]
  #  redirect_to books_path
  #end
end

app/controllers/interface/books_controller.rb
class Interface::BooksController < ActionController::Base

  def all
    render :json => {
      :sex => 'male',
      :age => '18',
      name: '小王'
    }
  end

  def index
    books = Book.where("name like '%#{params[:query]}%'")
    books = Book.all
    #all_books=Book.all.map do |the_book|{
    #:name => the_book.name,
    #:author => the_book.author
    #}
    #end
    render :json =>{
      "success":"ok",
      #"result": all_books
      #"result":books
      :result=>books
    }
  end

  def destroy
    book = Book.find params[:id]
    book.delete
    render :json =>{
      :success =>"ok"
    }
  end

  def update
    book = Book.find params[:id]
    book.name= params[:name]
    book.author= params[:author]
    book.save
    render :json =>{
      :result =>'ok',
      :name =>book.name,
      :author =>book.author
    }
  end

  def create
    book= Book.create :name=> params[:name],:author=> params[:author]
    render :json => {
      :result => "ok",
      :name => book.name,
      :author =>book.author
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= form_for @book, :html=>{:id=>"form"} do |f| %>
  <div>请输入标题：<%= f.text_field :name, :title=>"lalalal"%></div><br/>
  <!--给input加title-->
  <div>请输入文本：<%= f.cktext_area :author %></div><br/>
  <%= f.submit "确定" %>
<% end %>
<!--
<% if @book.id.present?
     url = "/books/#{@book.id}"
     method = 'put'
   else
     url = "/books/"
     method = 'post'
end %>
 <%= form_tag url do %>
   <%= hidden_field_tag "_method", method %>
   <%= text_field_tag "book[name]", @book.name %><br/>
   <%= text_field_tag "book[author]", @book.author%><br/>
   <%= submit_tag "确定" %>
 <% end %>
-->

app/views/books/edit.html.erb
<h1>请对书名为<%=@book.name%>做出修改</h1>

<!--
<form action="/books/<%= @book.id%>" method="POST">

  <input type="hidden" name="_method" value="put">
  <input type="text" name="new_name" value="<%= @book.name%>">
  <br/>
  <input type="text" name="new_author" value="<%= @book.author%>">
  <br/>
  <input type="submit" value="确定">

</form>
-->
<h1>Listing Masks</h1>
<%= text_field_tag :just_date %>
<hr>
<%= text_field_tag :just_phone %>
<hr>
<%= text_field_tag :just_alpha %>
<hr>
<script>
$(function(){
  $('#just_date').mask('99/99/9999',{placeholder:"mm/dd/yyyy"});
  $('#just_phone').mask('999-9999-9999');
  $('#just_alpha').mask('aaa',{completed:function(){alert("You typed the following: "+this.val())}}); //只能输入三个字母
})
</script>
<%= render :partial =>"form"%>
<script type="text/javascript">

jQuery(document).ready(function ($) {
  var jssor_1_SlideoTransitions = [
    [{b:0,d:600,y:-290,e:{y:27}}],
    [{b:0,d:1000,y:185},{b:1000,d:500,o:-1},{b:1500,d:500,o:1},{b:2000,d:1500,r:360},{b:3500,d:1000,rX:30},{b:4500,d:500,rX:-30},{b:5000,d:1000,rY:30},{b:6000,d:500,rY:-30},{b:6500,d:500,sX:1},{b:7000,d:500,sX:-1},{b:7500,d:500,sY:1},{b:8000,d:500,sY:-1},{b:8500,d:500,kX:30},{b:9000,d:500,kX:-30},{b:9500,d:500,kY:30},{b:10000,d:500,kY:-30},{b:10500,d:500,c:{x:87.50,t:-87.50}},{b:11000,d:500,c:{x:-87.50,t:87.50}}],
    [{b:0,d:600,x:410,e:{x:27}}],
    [{b:-1,d:1,o:-1},{b:0,d:600,o:1,e:{o:5}}],
    [{b:-1,d:1,c:{x:175.0,t:-175.0}},{b:0,d:800,c:{x:-175.0,t:175.0},e:{c:{x:7,t:7}}}],
    [{b:-1,d:1,o:-1},{b:0,d:600,x:-570,o:1,e:{x:6}}],
    [{b:-1,d:1,o:-1,r:-180},{b:0,d:800,o:1,r:180,e:{r:7}}],
    [{b:0,d:1000,y:80,e:{y:24}},{b:1000,d:1100,x:570,y:170,o:-1,r:30,sX:9,sY:9,e:{x:2,y:6,r:1,sX:5,sY:5}}],
    [{b:2000,d:600,rY:30}],
    [{b:0,d:500,x:-105},{b:500,d:500,x:230},{b:1000,d:500,y:-120},{b:1500,d:500,x:-70,y:120},{b:2600,d:500,y:-80},{b:3100,d:900,y:160,e:{y:24}}],
    [{b:0,d:1000,o:-0.4,rX:2,rY:1},{b:1000,d:1000,rY:1},{b:2000,d:1000,rX:-1},{b:3000,d:1000,rY:-1},{b:4000,d:1000,o:0.4,rX:-1,rY:-1}]
      ];
    var jssor_1_options = {
      $AutoPlay: true,
      $Idle: 2000,
      $CaptionSliderOptions: {
        $Class: $JssorCaptionSlideo$,
        $Transitions: jssor_1_SlideoTransitions,
        $Breaks: [
          [{d:2000,b:1000}]
        ]
      },
      $ArrowNavigatorOptions: {
        $Class: $JssorArrowNavigator$
      },
      $BulletNavigatorOptions: {
        $Class: $JssorBulletNavigator$
      }
    };
    var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);
    /*responsive code begin*/
    /*you can remove responsive code if you don't want the slider scales while window resizing*/
    function ScaleSlider() {
      var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
      if (refSize) {
        refSize = Math.min(refSize, 600);
        jssor_1_slider.$ScaleWidth(refSize);
      }
      else {
        window.setTimeout(ScaleSlider, 30);
      }
    }
    ScaleSlider();
    $(window).bind("load", ScaleSlider);
    $(window).bind("resize", ScaleSlider);
    $(window).bind("orientationchange", ScaleSlider);
    /*responsive code end*/
});
</script>
<style>
/* jssor slider bullet navigator skin 01 css */
/*
.jssorb01 div           (normal)
.jssorb01 div:hover     (normal mouseover)
.jssorb01 .av           (active)
.jssorb01 .av:hover     (active mouseover)
.jssorb01 .dn           (mousedown)
 */
.jssorb01 {
  position: absolute;
}
                .jssorb01 div, .jssorb01 div:hover, .jssorb01 .av {
                  position: absolute;
                  /* size of bullet elment */
                  width: 12px;
                  height: 12px;
                  filter: alpha(opacity=70);
                  opacity: .7;
                  overflow: hidden;
                  cursor: pointer;
                  border: #000 1px solid;
                }
                .jssorb01 div { background-color: gray; }
                .jssorb01 div:hover, .jssorb01 .av:hover { background-color: #d3d3d3; }
                .jssorb01 .av { background-color: #fff; }
                .jssorb01 .dn, .jssorb01 .dn:hover { background-color: #555555; }
                /* jssor slider arrow navigator skin 02 css */
                /*
                .jssora02l                  (normal)
                .jssora02r                  (normal)
                .jssora02l:hover            (normal mouseover)
                .jssora02r:hover            (normal mouseover)
                .jssora02l.jssora02ldn      (mousedown)
                .jssora02r.jssora02rdn      (mousedown)
                .jssora02l.jssora02lds      (disabled)
                .jssora02r.jssora02rds      (disabled)
                 */
                .jssora02l, .jssora02r {
                  display: block;
                  position: absolute;
                  /* size of arrow element */
                  width: 55px;
                  height: 55px;
                  cursor: pointer;
                  background: url('img/a02.png') no-repeat;
                  overflow: hidden;
                }
                .jssora02l { background-position: -3px -33px; }
                .jssora02r { background-position: -63px -33px; }
                .jssora02l:hover { background-position: -123px -33px; }
                .jssora02r:hover { background-position: -183px -33px; }
                .jssora02l.jssora02ldn { background-position: -3px -33px; }
                .jssora02r.jssora02rdn { background-position: -63px -33px; }
                .jssora02l.jssora02lds { background-position: -3px -33px; opacity: .3; pointer-events: none; }
                .jssora02r.jssora02rds { background-position: -63px -33px; opacity: .3; pointer-events: none; }
</style>
<div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 600px; height: 300px; overflow: hidden; visibility: hidden;">
  <!-- Loading Screen -->
  <div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
    <div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
    <div style="position:absolute;display:block;background:url('img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
  </div>
  <div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 600px; height: 300px; overflow: hidden;">
    <div data-p="112.50">
      <img data-u="image" src="/img/002.jpg" />
      <div data-u="caption" data-t="0" style="position: absolute; top: 320px; left: 30px; width: 350px; height: 30px; background-color: rgba(235,81,0,0.5); font-size: 20px; color: #ffffff; line-height: 30px; text-align: center;">mobile ready, touch swipe</div>
    </div>
    <div data-p="112.50" style="display: none;">
      <img data-u="image" src="/img/007.jpg" />
      <div data-u="caption" data-t="1" data-3d="1" style="position: absolute; top: -50px; left: 125px; width: 350px; height: 30px; background-color: rgba(235,81,0,0.5); font-size: 20px; color: #ffffff; line-height: 30px; text-align: center;">time lined layer animation</div>
    </div>
    <div data-p="112.50" style="display: none;">
      <img data-u="image" src="/img/003.jpg" />
      <div data-u="caption" data-t="2" style="position: absolute; top: 30px; left: -380px; width: 350px; height: 30px; background-color: rgba(235,81,0,0.5); font-size: 20px; color: #ffffff; line-height: 30px; text-align: center;">finger catchable right to left</div>
    </div>
    <div data-p="112.50" style="display: none;">
      <img data-u="image" src="/img/004.jpg" />
      <div data-u="caption" data-t="3" style="position: absolute; top: 30px; left: 30px; width: 350px; height: 30px; background-color: rgba(235,81,0,0.5); font-size: 20px; color: #ffffff; line-height: 30px; text-align: center;">responsive, scale smoothly</div>
    </div>
    <div data-p="112.50" style="display: none;">
      <img data-u="image" src="/img/005.jpg" />
      <div data-u="caption" data-t="4" style="position: absolute; top: 30px; left: 30px; width: 350px; height: 30px; background-color: rgba(235,81,0,0.6); font-size: 20px; color: #ffffff; line-height: 30px; text-align: center;">image, text, and custom layers</div>
    </div>
    <div data-p="112.50" style="display: none;">
      <img data-u="image" src="/img/006.jpg" />
      <div data-u="caption" data-t="5" style="position: absolute; top: 30px; left: 600px; width: 350px; height: 30px; background-color: rgba(235,81,0,0.5); font-size: 20px; color: #ffffff; line-height: 30px; text-align: center;">tons of transition type</div>
    </div>
    <div data-p="112.50" style="display: none;">
      <img data-u="image" src="/img/009.jpg" />
      <div data-u="caption" data-t="6" style="position: absolute; top: 30px; left: 30px; width: 350px; height: 30px; background-color: rgba(235,81,0,0.5); font-size: 20px; color: #ffffff; line-height: 30px; text-align: center;">visual slider maker</div>
    </div>
    <div data-b="0" data-p="112.50" style="display: none;">
      <img data-u="image" src="/img/008.jpg" />
      <div data-u="caption" data-t="7" style="position: absolute; top: -50px; left: 30px; width: 350px; height: 30px; background-color: rgba(235,81,0,0.5); font-size: 20px; color: #ffffff; line-height: 30px; text-align: center;">play in and play out</div>
    </div>
    <div data-p="112.50" style="display: none;">
      <img data-u="image" src="/img/011.jpg" />
      <div data-u="caption" data-t="8" data-3d="1" style="position: absolute; top: 25px; left: 150px; width: 250px; height: 250px; background-color: rgba(40,177,255,0.6); overflow: hidden;">
        <div data-u="caption" data-t="9" style="position: absolute; top: 100px; left: 25px; width: 200px; height: 50px; font-size: 24px; line-height: 50px;">A Child Layer</div>
      </div>
    </div>
    <div data-p="112.50" style="display: none;">
      <img data-u="image" src="/img/010.jpg" />
      <div data-u="caption" data-t="10" data-3d="1" style="position: absolute; top: 25px; left: 100px; width: 250px; height: 250px; background-color: rgba(40,177,255,0.6);">
        <div style="margin: 15px; font-size: 20px;">
          <p>This is full customized content layer.<br />
          </p>
          <p>
          Everything is allowed
          </p>
          You can put
          <a href="http://wwww.jssor.com">
            a link
          </a> or an image
          <img src="/img/icon_chrome.png" /> here.
        </div>
      </div>
    </div>
    <a data-u="any" href="http://www.jssor.com" style="display:none">Image Slider</a>
  </div>
  <!-- Bullet Navigator -->
  <div data-u="navigator" class="jssorb01" style="bottom:16px;right:16px;">
    <div data-u="prototype" style="width:12px;height:12px;"></div>
  </div>
  <!-- Arrow Navigator -->
  <span data-u="arrowleft" class="jssora02l" style="top:0px;left:8px;width:55px;height:55px;" data-autocenter="2"></span>
  <span data-u="arrowright" class="jssora02r" style="top:0px;right:8px;width:55px;height:55px;" data-autocenter="2"></span>
</div>

app/views/books/index.html.erb
<h1 align="center">我的书籍列表主页</h1>

<p align="center"><font color="red"> 总共<%= @books.size %>条记录</font></p>

<form action='/books' method='GET' >
  <input type='text' name='query' />
  <input type='submit' value='查询！'/>
</form>

<table align="center" border="1" bordercolor="blue">
  <tr>
    <th>书名</th>
    <th>作者</th>
    <th>操作</th>
  </tr>
  <% @books.each do |book|%>
    <tr>
      <td>
        <!--给某一列加link-->
        <%= link_to book.name%>
      </td>
      <td>
        <%= raw book.author%>
      </td>
      <td>
        <%=link_to "查看",book_path(:id => book.id)%>
        <%=link_to "编辑", edit_book_path(:id => book.id)%>
        <%=link_to "删除", "/books/#{book.id}", :method =>"delete",:data=> {:confirm => "确定要删除吗?"}%>
      </td>
    </tr>
  <%end%>
</table>

<p align="center"><%=link_to "新增一本书", new_book_path%></p>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<style>
  dialog label, #dialog input { display:block; }
  #dialog label { margin-top: 0.5em; }
  #dialog input, #dialog textarea { width: 95%; }
  #tabs { margin-top: 1em; }
  #tabs li .ui-icon-close { float: left; margin: 0.4em 0.2em 0 0; cursor: pointer; }
  #add_tab { cursor: pointer;float: left;}
  #tabs{position: relative;top: 50px;}
</style>
<script>
$( function() {
  var tabTitle = $( "#tab_title" ),
  tabContent = $( "#tab_content" ),
  tabTemplate = "<li><a href='#{href}'>#{label}</a> <span class='ui-icon ui-icon-close' role='presentation'>Remove Tab</span></li>",
  tabCounter = 2;

  var tabs = $( "#tabs" ).tabs();

  // Modal dialog init: custom buttons and a "close" callback resetting the form inside
  var dialog = $( "#dialog" ).dialog({
    autoOpen: false,
    modal: true,
    buttons: {
      Add: function() {
        addTab();
        $( this ).dialog( "close" );
      },
      Cancel: function() {
        $( this ).dialog( "close" );
      }
    },
    close: function() {
      form[ 0 ].reset();
    }
  });

  // AddTab form: calls addTab function on submit and closes the dialog
  var form = dialog.find( "form" ).on( "submit", function( event ) {
    addTab();
    dialog.dialog( "close" );
    event.preventDefault();
  });
  // Actual addTab function: adds new tab using the input from the form above
  function addTab() {
    var label = tabTitle.val() || "Tab " + tabCounter,
    id = "tabs-" + tabCounter,
    li = $( tabTemplate.replace( /#\{href\}/g, "#" + id ).replace( /#\{label\}/g, label ) ),
    tabContentHtml = tabContent.val() || "Tab " + tabCounter + " content.";

    tabs.find( ".ui-tabs-nav" ).append( li );
    tabs.append( "<div id='" + id + "'><p>" + tabContentHtml + "</p></div>" );
    tabs.tabs( "refresh" );
    tabCounter++;
  }

  // AddTab button: just opens the dialog
  $( "#add_tab" )
    .button()
    .on( "click", function() {
      dialog.dialog( "open" );
    });

  // Close icon: removing the tab on click
  tabs.on( "click", "span.ui-icon-close", function() {
    var panelId = $( this ).closest( "li" ).remove().attr( "aria-controls" );
    $( "#" + panelId ).remove();
    tabs.tabs( "refresh" );
  });

  tabs.on( "keyup", function( event ) {
    if ( event.altKey && event.keyCode === $.ui.keyCode.BACKSPACE ) {
      var panelId = tabs.find( ".ui-tabs-active" ).remove().attr( "aria-controls" );
      $( "#" + panelId ).remove();
      tabs.tabs( "refresh" );
    }
  });
} );
</script>

<div id="dialog" title="Tab data">
  <form>
    <fieldset class="ui-helper-reset">
      <label for="tab_title">Title</label>
      <input type="text" name="tab_title" id="tab_title" value="Tab Title" class="ui-widget-content ui-corner-all">
      <label for="tab_content">Content</label>
      <textarea name="tab_content" id="tab_content" class="ui-widget-content ui-corner-all">Tab content</textarea>
    </fieldset>
  </form>
</div>

<button id="add_tab">Add Tab</button>

<div id="tabs">
  <ul>
    <li><a href="#tabs-1">Nunc tincidunt</a> <span class="ui-icon ui-icon-close" role="presentation">Remove Tab</span></li>
  </ul>
  <div id="tabs-1">
    <p>Proin elit arcu, rutrum commodo, vehicula tempus, commodo a, risus. Curabitur nec arcu. Donec sollicitudin mi sit amet mauris. Nam elementum quam ullamcorper ante. Etiam aliquet massa et lorem. Mauris dapibus lacus auctor risus. Aenean tempor ullamcorper leo. Vivamus sed magna quis ligula eleifend adipiscing. Duis orci. Aliquam sodales tortor vitae ipsum. Aliquam nulla. Duis aliquam molestie erat. Ut et mauris vel pede varius sollicitudin. Sed ut dolor nec orci tincidunt interdum. Phasellus ipsum. Nunc tristique tempus lectus.</p>
  </div>
</div>

app/views/books/new.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<h1>新增加一本书</h1>
<!--
  <form action="/books" method="POST">
  <input type="text" name="new_name">
  <br/>
  <input type="text" name="new_author">
  <br/>
  <input type="submit" value="确定">
  </form>
-->

<%=render :partial =>"form" %>

<style>
label {
  display: inline-block; width: 5em;
}
    fieldset div {
      margin-bottom: 2em;
    }
    fieldset .help {
      display: inline-block;
    }
    .ui-tooltip {
      width: 210px;
    }
</style>
<script>
$( function() {
  var tooltips = $( "[title]" ).tooltip({
    position: {
      my: "left top",
      at: "right+5 top-5",
      collision: "none"
    }
  });
  $( "#help" )
    .text( "Show help" )
    .button()
    .on( "click", function() {
      tooltips.tooltip( "open" );
    })
} );
</script>
<form>
  <fieldset>
    <div>
      <label for="firstname">Firstname</label>
      <input id="firstname" name="firstname" title="Please provide your firstname.">
    </div>
    <div>
      <label for="lastname">Lastname</label>
      <input id="lastname" name="lastname" title="Please provide also your lastname.">
    </div>
    <div>
      <label for="address">Address</label>
      <input id="address" name="address" title="Your home or work address.">
    </div>
  </fieldset>
</form>
<button id="help"></button>

<style>
input.error{border:1px solid red}
label.error {
  padding-left: 16px;
  padding-bottom: 2px;
  font-weight: bold;
  color: #EA5200;
}
</style>

<script>
$("#form").validate({
  rules:{
    "book[name]":"required",
    "book[author]":{
      "required":true,
      "rangelength":[6,10]
    }
  },
  messages:{
    "book[name]":"请输入标题",
    "book[author]":{
      "required":"请输入内容",
      "rangelength":"用户名在6-10位"
    }
  }
});
</script>


<script>
$(function() {
  $( "#dialog" ).dialog({
    autoOpen:false,
    show: {
      effect: "blind",
      duration: 1000
    },
    hide: {
      effect: "explode",
      duration: 1000
    }
  });

  $( "#opener" ).click(function() {
    $( "#dialog" ).dialog('open');
  });
});
</script>
<div id="dialog" title="弹出框">
  <p>这时一个简单的弹出窗口页面，该页面可以被移动，改变大小，关闭。</p>
</div>
<button id="opener">点击我弹出窗口</button>



<script>
$( function() {
  $( "#datepicker" ).datepicker();
} );
</script>
<p>Date: <input type="text" id="datepicker"></p>

app/views/books/show.html.erb
<h1>详情页</h1>
书名：<%=@book.name%></br>
书作者：<%=@book.author%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyLibrary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/two.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Two Layout!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<hr/>
<%= yield %>
<hr/>
</body>
</html>